apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-toolkit-deployment
spec:
  selector:
    matchLabels:
      app: kube-toolkit
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-toolkit
    spec:
      containers:
      - name: kube-toolkit
        image: registry.cn-hangzhou.aliyuncs.com/iuxt/kube-toolkit:1
        ports:
        - containerPort: 8080
        env:
          - name: SERVER_PORT
            value: "8080"
          - name: ECHO_ENV
            value: "NODE_NAME,POD_NAME,POD_NAMESPACE,POD_IP"
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP


---
apiVersion: v1
kind: Service
metadata:
  name: kube-toolkit-service
spec:
  selector:
    app: kube-toolkit
  ports:
  - protocol: TCP
    port: 80                # 这个是service对外暴露的端口
    targetPort: 8080          # 这里是pod对外暴露的端口
    nodePort: 30081
  type: NodePort


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-toolkit
  annotations:
    client.ingress.kubernetes.io/ssl-redirect: "false" # 关闭SSL跳转
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - test.i.com
    secretName: i-com
  rules:
  - host: test.i.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-toolkit-service
            port:
              number: 80
